local M = {}
-- local palette = require("nvim-quietlight.palette.quiet")
M.hl_group = function(palette)
	return {
		Normal = {
			fg = palette.gui.black._50,
			bg = palette.gui.white._50,
			ctermfg = palette.cterm.gray._0,
			ctermbg = palette.cterm.white._50,
		},
		-- NormalNC
		NormalFloat = {
			fg = palette.gui.black._50,
			bg = palette.gui.white._50,
			ctermfg = palette.cterm.gray._0,
			ctermbg = palette.cterm.white._50,
		},
		ColorColumn = {
			fg = palette.gui.transparent,
			bg = palette.gui.gray._100,
			ctermfg = palette.cterm.transparent,
			ctermbg = palette.cterm.gray._100,
		},
		--
		CursorColumn = {
			fg = palette.gui.transparent,
			bg = palette.gui.green._150,
			ctermfg = palette.cterm.transparent,
			ctermbg = palette.cterm.green._100,
		},
		CursorLine = {
			fg = palette.gui.transparent,
			bg = palette.gui.green._150,
			ctermfg = palette.cterm.transparent,
			ctermbg = palette.cterm.green._100,
		},
		Directory = {
			fg = palette.gui.blue._100,
			bg = palette.gui.transparent,
			ctermfg = palette.cterm.blue._100,
			ctermbg = palette.cterm.transparent,
		},
		DiffAdd = {
			fg = palette.gui.black._50,
			bg = palette.gui.green._50,
			ctermfg = palette.cterm.green._0,
			ctermbg = palette.cterm.white._50,
		},
		DiffChange = {
			fg = palette.gui.black._50,
			bg = palette.gui.orange._0,
			ctermfg = palette.cterm.gray._0,
			ctermbg = palette.cterm.orange._0,
		},
		DiffDelete = {
			fg = palette.gui.white._50,
			bg = palette.gui.red._50,
			ctermfg = palette.cterm.white._50,
			ctermbg = palette.cterm.red._1000,
		},
		DiffText = {
			fg = palette.gui.white._50,
			bg = palette.gui.blue._100,
			ctermfg = palette.cterm.white._50,
			ctermbg = palette.cterm.blue._100,
		},
		ErrorMsg = {
			fg = palette.gui.white._50,
			bg = palette.gui.red._50,
			ctermfg = palette.cterm.white._0,
			ctermbg = palette.cterm.red._100,
		},
		VertSplit = {
			fg = palette.gui.gray._100,
			bg = palette.gui.transparent,
			ctermfg = palette.cterm.gray._100,
			ctermbg = palette.cterm.transparent,
		},
		Folded = {
			fg = palette.gui.black._50,
			bg = palette.gui.green._0,
			ctermfg = palette.cterm.gray._0,
			ctermbg = palette.cterm.gray._100,
		},
		FoldColumn = {
			fg = palette.gui.transparent,
			bg = palette.gui.green._0,
			ctermfg = palette.cterm.gray.transparent,
			ctermbg = palette.cterm.gray._100,
		},
		SignColumn = {
			fg = palette.gui.transparent,
			bg = palette.gui.white._50,
			ctermfg = palette.cterm.transparent,
			ctermbg = palette.cterm.white._50,
		},
		LineNr = {
			fg = palette.gui.black._50,
			bg = palette.gui.transparent,
			ctermfg = palette.cterm.gray._0,
			ctermbg = palette.cterm.white.transparent,
		},
		CursorLineNr = {
			fg = palette.gui.purple._0,
			bg = palette.gui.transparent,
			bold = true,
			ctermfg = palette.cterm.purple._0,
			ctermbg = palette.cterm.white.transparent,
		},
		MatchParen = {
			fg = palette.gui.black._50,
			bg = palette.gui.green._100,
			ctermfg = palette.cterm.gray._0,
			ctermbg = palette.cterm.green._50,
		},
		ModeMsg = {
			fg = palette.gui.green._50,
			bg = palette.gui.transparent,
			ctermfg = palette.cterm.green._0,
			ctermbg = palette.cterm.transparent,
		},
		MoreMsg = {
			fg = palette.gui.green._50,
			bg = palette.gui.transparent,
			ctermfg = palette.cterm.green._0,
			ctermbg = palette.cterm.transparent,
		},
		NonText = {
			fg = palette.gui.gray._100,
			bg = palette.gui.transparent,
			ctermfg = palette.cterm.gray._100,
			ctermbg = palette.cterm.transparent,
		},
		Pmenu = {
			fg = palette.gui.black._50,
			bg = palette.gui.white._50,
			ctermfg = palette.cterm.gray._0,
			ctermbg = palette.cterm.white._50,
		},
		PmenuSel = {
			fg = palette.gui.green._100,
			bg = palette.gui.black._50,
			reverse = true,
			ctermfg = palette.cterm.green._50,
			ctermbg = palette.cterm.gray._0,
		},
		InfoPopup = {
			fg = palette.gui.black._50,
			bg = palette.gui.white._50,
			ctermfg = palette.cterm.gray._0,
			ctermbg = palette.cterm.white._50,
		},
		Question = {
			fg = palette.gui.green._50,
			bg = palette.gui.transparent,
			ctermfg = palette.cterm.green._0,
			ctermbg = palette.cterm.transparent,
		},
		Search = {
			fg = palette.gui.white._50,
			bg = palette.gui.purple._150,
			ctermfg = palette.cterm.white._50,
			ctermbg = palette.cterm.purple._100,
		},
		SpecialKey = {
			fg = palette.gui.gray._100,
			bg = palette.gui.transparent,
			ctermfg = palette.cterm.gray._100,
			ctermbg = palette.cterm.transparent,
		},
		SpellCap = {
			fg = palette.gui.blue._0,
			bg = palette.gui.transparent,
			undercurl = true,
			ctermfg = palette.cterm.blue._0,
			ctermbg = palette.cterm.transparent,
		},
		SpellLocal = {
			fg = palette.gui.blue._50,
			bg = palette.gui.cyan._0,
			underline = true,
			ctermfg = palette.cterm.blue._150,
			ctermbg = palette.cterm.blue._50,
		},
		SpellBad = {
			fg = palette.gui.red._0,
			bg = palette.gui.transparent,
			undercurl = true,
			ctermfg = palette.cterm.red._0,
			ctermbg = palette.cterm.transparent,
		},
		SpellRare = {
			fg = palette.gui.purple._50,
			bg = palette.gui.purple._0,
			underline = true,
			ctermfg = palette.cterm.purple._50,
			ctermbg = palette.cterm.purple._0,
		},
		StatusLine = {
			fg = palette.gui.purple._100,
			bg = palette.gui.white._50,
			reverse = true,
			bold = true,
			ctermfg = palette.cterm.purple._100,
			ctermbg = palette.cterm.white._50,
		},
		StatusLineNC = {
			fg = palette.gui.purple._150,
			bg = palette.gui.white._50,
			reverse = true,
			bold = true,
			ctermfg = palette.cterm.purple._100,
			ctermbg = palette.cterm.white._50,
		},
		StatusLineTerm = {
			fg = palette.gui.purple._100,
			bg = palette.gui.white._50,
			reverse = true,
			bold = true,
			ctermfg = palette.cterm.purple._100,
			ctermbg = palette.cterm.white._50,
		},
		StatusLineTermNC = {
			fg = palette.gui.purple._150,
			bg = palette.gui.white._50,
			reverse = true,
			bold = true,
			ctermfg = palette.cterm.purple._100,
			ctermbg = palette.cterm.white._50,
		},
		TabLine = {
			fg = palette.gui.black._50,
			bg = palette.gui.gray._50,
			ctermfg = palette.cterm.gray._0,
			ctermbg = palette.cterm.gray._100,
		},
		TabLineFill = {
			fg = palette.gui.white._50,
			bg = palette.gui.white._50,
			reverse = true,
			ctermfg = palette.cterm.white._50,
			ctermbg = palette.cterm.white._50,
		},
		EndOfBuffer = {
			fg = palette.gui.white._50,
			bg = palette.gui.white._50,
			ctermfg = palette.cterm.white._50,
			ctermbg = palette.cterm.white._50,
		},
		Title = {
			fg = palette.gui.red._50,
			bg = palette.gui.transparent,
			bold = true,
			ctermfg = palette.cterm.red._100,
			ctermbg = palette.cterm.transparent,
		},
		Visual = {
			fg = palette.gui.white._50,
			bg = palette.gui.gray._100,
			reverse = true,
			ctermfg = palette.cterm.white._50,
			ctermbg = palette.cterm.gray._100,
		},
		WarningMsg = {
			fg = palette.gui.green._100,
			bg = palette.gui.transparent,
			ctermfg = palette.cterm.green._50,
			ctermbg = palette.cterm.transparent,
		},
		WildMenu = {
			fg = palette.gui.black._50,
			bg = palette.gui.green._100,
			ctermfg = palette.cterm.gray._0,
			ctermbg = palette.cterm.green._50,
		},
		LongLineWarning = {
			fg = palette.gui.transparent,
			bg = palette.gui.yellow._0,
			underline = true,
			ctermfg = palette.cterm.transparent,
			ctermbg = palette.cterm.transparent,
		},
		Underlined = {
			fg = palette.gui.blue._100,
			bg = palette.gui.transparent,
			ctermfg = palette.cterm.gray._0,
			ctermbg = palette.cterm.transparent,
		},
		Ignore = {
			fg = palette.gui.transparent,
			bg = palette.gui.transparent,
			ctermfg = palette.cterm.transparent,
			ctermbg = palette.cterm.transparent,
		},
		Error = {
			fg = palette.gui.red._0,
			bg = palette.gui.transparent,
			undercurl = true,
			ctermfg = palette.cterm.red._0,
			ctermbg = palette.cterm.transparent,
		},
		Todo = {
			fg = palette.gui.black._50,
			bg = palette.gui.transparent,
			bold = true,
			ctermfg = palette.cterm.gray._0,
			ctermbg = palette.cterm.transparent,
		},
		qfLineNr = {
			fg = palette.gui.yellow._0,
			bg = palette.gui.transparent,
			bold = true,
			ctermfg = palette.cterm.yellow._0,
			ctermbg = palette.cterm.transparent,
		},

		-- diff
		diffAdded = {
			fg = palette.gui.green._50,
			bg = palette.gui.transparent,
			ctermfg = palette.cterm.green._0,
			ctermbg = palette.cterm.transparent,
		},
		diffRemoved = {
			fg = palette.gui.orange._0,
			bg = palette.gui.transparent,
			ctermfg = palette.cterm.orange._0,
			ctermbg = palette.cterm.transparent,
		},
		FloatBorder = {
			fg = palette.gui.gray._100,
			bg = palette.gui.transparent,
			ctermfg = palette.cterm.gray._100,
			ctermbg = palette.cterm.transparent,
		},
	}
end
return M
